export const ADD_TO_CART = "ADD_TO_CART";
export const INCREASE_QUANTITY_CART = "INCREASE_QUANTITY_CART";
export const DECREASE_QUANTITY_CART = "DECREASE_QUANTITY_CART";
export const UPDATE_QUANTITY_CART = "UPDATE_QUANTITY_CART";
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
export const REMOVE_ALL_CART = "REMOVE_ALL_CART";
export const SAVE_SHIPPING_INFO = "SAVE_SHIPPING_INFO";
